version: "3.0"

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-one
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/
            - ./final.conf:/etc/nginx/conf.d/default.conf

    # mysql:
    #     image: mysql
    #     container_name: mysql
    #     ports:
    #         -   3306:3306
    #     volumes:
    #         -   mysqldata:/var/lib/mysql
    #     environment:
    #         -  MYSQL_DATABASE=${DB_DATABASE}
    #         -  MYSQL_USER=${DB_USERNAME}
    #         -  MYSQL_PASSWORD=${DB_PASSWORD}
    #         -  MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /var/www/vendor
            - ./:/var/www/

volumes:
    mysqldata:
